=== uo225211/sew23/xml/rutas.xsd
<?xml version="1.0" encoding="utf-8"?>
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreRuta" />
				<xs:element ref="medioTransporte" />
				<xs:element ref="inicio" />
				<xs:element ref="duración" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="personasAdecuadas" />
				<xs:element ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="tipo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreRuta" type="xs:string" />
	<xs:element name="medioTransporte" type="xs:string" />
	<xs:element name="inicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="lugar" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />	
	<xs:element name="hora" type="xs:string" />
	<xs:element name="lugar">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="direccion" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="direccion" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
			<xs:attribute name="tipo" type="tipo_Coordenadas" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:float" />
	<xs:element name="latitud" type="xs:float" />
	<xs:element name="altitud" type="xs:float" />
	<xs:element name="duración" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="personasAdecuadas" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0" />
				<xs:maxInclusive value="10" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreHito" />
				<xs:element ref="descipcionHito" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreHito" type="xs:string" />
	<xs:element name="descipcionHito" type="xs:string" />
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />



	<xs:simpleType name="tipo_Coordenadas">
		<xs:restriction base="xs:string">
			<xs:enumeration value="origen"/>
			<xs:enumeration value="hito"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== uo225211/sew23/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
    <!--Tipo
    de ruta (por ejemplo “Arquitectura y monumentos”, “Gastronómica”,
    “Paisajística”, “Mixta tapas y monumentos”, “Escalada”, “Senderismo”, etc.)-->
    <ruta tipo="Arquitectura y monumentos">
        <nombreRuta> La República Checa en 10 DÍAS</nombreRuta>
        <medioTransporte>Coche</medioTransporte>
        <inicio>
            <fecha>2024-01-31</fecha>
            <hora>09:00</hora>
            <lugar nombre="Ciudad Vieja">
                <direccion> Michalská 510/8, 110 00 Staré Město, Chequia</direccion>
                <coordenadas tipo="origen">
                    <longitud>14.420085423299167</longitud>
                    <latitud>50.08518189196055</latitud>
                    <altitud>399</altitud>
                </coordenadas>
            </lugar>
        </inicio>
        <duración>P10D</duración>
        <agencia>NaturaMundo</agencia>
        <descripcion>Si tienes un par de semanas para realizar un viaje, y el interés de visitar
            Praga, te propongo este fantástico destino. La República Checa es, salvo su capital, un
            lugar bastante desconocido. Cuando buscas información para visitar el país es difícil
            encontrar algo que no hable solo de Praga, por eso pasé días y días organizando esta
            ruta por la República Checa. Fue un viaje increíble y te dejo aquí por escrito toda la
            información por si te apetece disfrutar de todo lo que ofrece este país. Comenzamos con
            esta guía de la ruta por la República Checa de 10 días.</descripcion>
        <!--Personas
        adecuadas para la ruta (por ejemplo “Se puede ir con niños”, “Personas en buena forma
        física”, “tercera edad”, etc.)-->
        <personasAdecuadas>Todas</personasAdecuadas>
        <referencias>
            <referencia>https://www.marcateunviaje.com/ruta-por-la-republica-checa/</referencia>
            <referencia>https://es.wikipedia.org/wiki/Ciudad_vieja_(Praga)</referencia>
            <referencia>https://www.prague.eu/es/informacion-practica/sobre-la-republica-checa-17143</referencia>
        </referencias>
        <!--Recomendación
        de la ruta de 0 a 10 (por ejemplo “7”)-->
        <recomendacion>8</recomendacion>
        <!--Hitos
        de la ruta con algún tipo de atractivo turístico (mínimo 3 hitos)-->
        <hitos>
            <hito>
                <nombreHito>Días 1, 2 y 3</nombreHito>
                <descipcionHito>Pasar 3 días visitando la hermosa ciudad de Pragra</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>14.420085423299167</longitud>
                    <latitud>50.08518189196055</latitud>
                    <altitud>399</altitud>
                </coordenadas>
                <distancia unidades="km">0</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>praga1.jpg</foto>
                    <foto>praga2.jpg</foto>
                    <foto>praga3.jpg</foto>
                </fotos>
                <videos>
                </videos>
            </hito>
            <hito>
                <nombreHito>Día 4</nombreHito>
                <descipcionHito>KARLŠTEJN, KRIVOKLÁT, LOKET Y PILSEN</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>14.183849895083169</longitud>
                    <latitud>49.9344744226256</latitud>
                    <altitud>345</altitud>
                </coordenadas>
                <distancia unidades="km">37.8</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>karl.jpg</foto>
                    <foto>krivoklat.jpg</foto>
					<foto>loket.jpg</foto>
                    <foto>pilsen.jpg</foto>
                </fotos>
                <videos>                    
                </videos>
            </hito>
            <hito>
                <nombreHito>Día 5</nombreHito>
                <descipcionHito>ZVÍKOV, HOLAŠOVICE Y CESKÝ KRUMLOV</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>14.192511732655829</longitud>
                    <latitud>49.45375014956525</latitud>
                    <altitud>370</altitud>
                </coordenadas>
                <distancia unidades="km">96.3</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>zvikov.jpg</foto>
                    <foto>krumlov.jpg</foto>
                    <foto>holasovice.jpg</foto>
                </fotos>
                <videos>
                </videos>
            </hito>
			<hito>
                <nombreHito>Día 6</nombreHito>
                <descipcionHito>CESKÉ BUDEJOVICE, HLUBOKÁ, TREBON, TELC Y TREBÍC</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>14.478530904369235</longitud>
                    <latitud>48.97826791193981</latitud>
                    <altitud>381</altitud>
                </coordenadas>
                <distancia unidades="km">24.5</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>cerke.jpg</foto>
                    <foto>hluboka.jpg</foto>
                    <foto>trebon.jpg</foto>
					<foto>telc.jpg</foto>
					<foto>trebic.jpg</foto>
                </fotos>
                <videos>
                </videos>
            </hito>
			<hito>
                <nombreHito>Día 7</nombreHito>
                <descipcionHito>BRNO, LEDNICE Y MIKULOV</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>16.614352709557256</longitud>
                    <latitud>49.20005113588766</latitud>
                    <altitud>237</altitud>
                </coordenadas>
                <distancia unidades="km">76.2</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>brno.jpg</foto>
                    <foto>mikulov.jpg</foto>
                    <foto>lednice.jpg</foto>
                </fotos>
                <videos>
                </videos>
            </hito>
			<hito>
                <nombreHito>Día 8</nombreHito>
                <descipcionHito>OLOMOUC Y BOUZOV</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>17.254812220841213</longitud>
                    <latitud>49.591112735639996</latitud>
                    <altitud>219</altitud>
                </coordenadas>
                <distancia unidades="km">125.7</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>olomouc.jpg</foto>
                    <foto>bouzov.jpg</foto>
                </fotos>
                <videos></videos>
            </hito>
			<hito>
                <nombreHito>Día 9</nombreHito>
                <descipcionHito>KUTNÁ HORA, CESKY STERNBERK Y KONOPIŠTE</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>15.270841268494163</longitud>
                    <latitud>49.94756456885061</latitud>
                    <altitud>254</altitud>
                </coordenadas>
                <distancia unidades="km">165.5</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>kutna.jpg</foto>
                    <foto>sternberk.jpg</foto>
                    <foto>konopiste.jpg</foto>
                </fotos>
                <videos>
                </videos>
            </hito>
			<hito>
                <nombreHito>Día 10</nombreHito>
                <descipcionHito>CAMPO DE CONCENTRACIÓN DE TEREZÍN</descipcionHito>
                <!-- Coordenadas geográficas del hito: longitud, latitud, altitud-->
                <coordenadas tipo="hito">
                    <longitud>14.167166943278723</longitud>
                    <latitud>50.51584806027002</latitud>
                    <altitud>150</altitud>
                </coordenadas>
                <distancia unidades="km">107.2</distancia>
                <fotos>
                    <!--–
                    Galería de fotografías del hito (mínimo 1, máximo 5)-->
                    <foto>terezin.jpg</foto>
                </fotos>
                <videos>
                </videos>
            </hito>
        </hitos>
    </ruta>
	    <ruta tipo="Senderismo">
        <nombreRuta>Hrensko - Puerta de Pravcice - Río Kamenice</nombreRuta>
        <medioTransporte>A pie</medioTransporte>
        <inicio>
            <fecha>2024-03-28</fecha>
            <hora>09:00</hora>
